# Generated by Django 5.1.1 on 2024-11-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversa_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
