# Generated by Django 5.1.1 on 2024-11-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_mensagem_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='id_tipo_mensagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chatbot.tipomensagem'),
        ),
    ]
