# Generated by Django 5.1.1 on 2024-12-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_tipomensagem_id_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='conversa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testes', to='chatbot.conversa'),
        ),
    ]
